name: CI

on:
  workflow_dispatch:

jobs:
  main_job:
    name: Main job
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_VERSION: 1.3.9
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash

    steps:
      - name: Install kubelogin
        run: |
          sudo apt update
          sudo snap install kubelogin

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check prerequisites
        run: ./setup.1.sh
