name: CI

on:
  workflow_dispatch:

jobs:
  main_job:
    name: Main job
    env:
      TF_VERSION: 1.3.9
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash

    steps:
      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install kubelogin
        run: |
          sudo apt-get update
          sudo snap install kubelogin

      - name: Checkout
        uses: actions/checkout@v3

      - name: Pre-Terraform setup
        run: ./setup.sh
